version: '3'
services:
  jenkins:
    image: 'jenkins/jenkins:latest'
    container_name: 'jenkins-casare-int'
    hostname: 'jenkins-casare-int'
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - '/srv/jenkins/jenkins_home:/var/jenkins_home'

  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    container_name: 'gitlab-casare-int'
    hostname: 'gitlab.casare.int'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.casare.int'
        gitlab_rails['smtp_enable'] = false
        gitlab_rails['initial_root_password'] = 'root1234'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
#      - '22:22'
      - '587:587'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
