Vagrant.configure("2") do |config|
  config.vm.define "checkmk" do |checkmk|
    checkmk.vm.box = "bento/centos-7"
    checkmk.vm.hostname = "checkmk.paradigmahouse.lan"
    
    checkmk.vm.network "public_network"
    checkmk.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
      v.name = "VagrantCheckMK"
    end
    config.vm.provision "shell", path: "instalacion.sh"
  end
end
