Vagrant.configure("2") do |config|
  config.vm.define "graylog" do |graylog|
    graylog.vm.box = "bento/centos-7"
    graylog.vm.hostname = "graylog.jddr.lan"
    
    graylog.vm.network "public_network"
    graylog.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 4
      v.name = "VagrantGraylog"
    end
    graylog.vm.provision "shell", path: "instalacion.sh"
  end
end
