version: '3.1'

services:
  php:
    container_name: website-casare-int
    image: php:7.4-apache
    ports:
      - 1234:80
    command: >
      bash -c "apt update -y &&
             apt install git -y &&
             git clone https://github.com/aramirol/simple-website.git /var/www/html &&
             tail -f /dev/null"
